# kind_config.yml
# Configuración para levantar un cluster kind con mapeo de puertos
# que permitirá exponer el Istio IngressGateway en tu máquina host.

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # Mapea el puerto 80 del ingressgateway al 8080 de tu host
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      # Mapea el puerto 443 del ingressgateway al 8443 de tu host
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
