apiVersion: apps/v1
kind: Deployment
metadata:
  name: academic-deployment
  labels:
    app: academic-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academic-service
  template:
    metadata:
      labels:
        app: academic-service
    spec:
      containers:
      - name: academic
        # Asume que construyes tu docker con tag `academic-service:latest`
        image: academic-service:latest
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: academic-service
  labels:
    app: academic-service
spec:
  selector:
    app: academic-service
  ports:
  - name: http
    port: 80          # puerto dentro del cluster
    targetPort: 8001  # puerto expuesto por el contenedor
