apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-deployment
  labels:
    app: security-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-service
  template:
    metadata:
      labels:
        app: security-service
    spec:
      containers:
      - name: security
        image: security-service:latest
        ports:
        - containerPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: security-service
  labels:
    app: security-service
spec:
  selector:
    app: security-service
  ports:
  - name: http
    port: 80
    targetPort: 8003
