apiVersion: apps/v1
kind: Deployment
metadata:
  name: solicitud-deployment
  labels:
    app: solicitud-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solicitud-service
  template:
    metadata:
      labels:
        app: solicitud-service
    spec:
      containers:
      - name: solicitud
        image: solicitud-service:latest
        ports:
        - containerPort: 8004
---
apiVersion: v1
kind: Service
metadata:
  name: solicitud-service
  labels:
    app: solicitud-service
spec:
  selector:
    app: solicitud-service
  ports:
  - name: http
    port: 80
    targetPort: 8004
